### ISSUE TITLE
Keep getting ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'

### ISSUE THREAD

**Issue by Anjerlaan** [electrolama/docs.electrolama.com#37]
Hi,

I have the ZZH stick for a while now, and updated 3 or 4 times firmware without any issues.
But now I keep getting the error after trying to get the stick into Bootloader mode:

`ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'`

What could be wrong suddenly?

**Comment by omerk** [comment]
This is the repo for documentation, please send an email to support@electrolama.com with your order ID if you need support.
